### ISSUE TITLE
Island owner offline issue.

### ISSUE THREAD

**Issue by bvanitem** [mastercake10/CustomOreGen#10]
I was curious if there is any fix to when the island owner is offline then it defaults back to the default generator. I would really appreciate it if you could help.

Thanks

**Comment by ridalarry** [comment]
Anything new about this?

**Comment by MattTek** [comment]
AdvancedOreGen (also developed by MasterCake) has offline owner support for generators. I’m unsure if he’ll ever add it to CustomOreGen, but my guess is no because it’s one of the big things that makes AOG unique from COG.

**Comment by mastercake10** [comment]
See @MattTek's comment
