### ISSUE TITLE
Bentobox Custom Cobblestonegenerator only works in the main world

### ISSUE THREAD

**Issue by Peda1996** [mastercake10/CustomOreGen#15]
I just wanted to add the feature, that users can use their nether, and end world for generating (different) custom ores. But the problem is, that the plugin doesn't recognize the end and the nether, therefore only default cobblestone is generated.

Would also be cool if you could enable water in nether with this plugin ^^

Is there any way of solving this?

**Comment by Peda1996** [comment]
The mistake is within the api, as it only returns the main world, and the nether and end is not returned.

I fixed it by adding the end and the nether to the world:


```
	@Override
	public String[] getSkyBlockWorldNames() {
		return api.getIWM().getOverWorlds().stream().map(w -> w.getName()).map(w -> new String[]{w,w+"_nether",w+"_the_end"}).flatMap(l -> Stream.of(l)).toArray(String[]::new);
	}
```

**Comment by mastercake10** [comment]
Hey, thanks for investigating in this. Could you create a PR?

**Comment by Peda1996** [comment]
Well, but i have rewritten the whole project structure, as i couldn't compile the project with the current pom.xml, also the plotsquared hook was missing.
