### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Thrasilias** [mastercake10/CustomOreGen#24]
where is the 1.14.4 code

**Comment by mastercake10** [comment]
on the dev branch.

**Comment by Thrasilias** [comment]
i think you messed up then, because i only see 1.12 there

**Comment by Thrasilias** [comment]
https://github.com/mastercake10/CustomOreGen/blob/dev/pom.xml#L55

**Comment by mastercake10** [comment]
I don't messed it up, all method used by custom ore gen haven't changed in new versions, that's why custom ore gen still has bukkit 1.12.2 as dependency.

**Comment by Thrasilias** [comment]
ahh ok
