### ISSUE TITLE
Total Chance

### ISSUE THREAD

**Issue by samidont0817** [mastercake10/CustomOreGen#29]
When reloading the plugin, it states that the generators do not have a total chance of 100.0, even though they do. 

CustomOreGen: v1.3.18-SNAPSHOT
FabledSkyBlock: v2.0.3
Server Version: Paper(192) 1.14.4-R0.1-SNAPSHOT
`# You can create generators as much as you want.
# Important: All generators should be named "generator1", "generator2", etc. 
# You can define the spawnrates of any block in the blocks-section.
# The spawnrates are in percent, for example 57.3 are 57,3%.
# All values together should be 100%. If all values together are higher or lower as 100, the plugin would'nt work correctly.
# The permissions are custom, so you can make a generator for VIPS, and give them the permission "oregen.vip".
# Are you finish with configuring? Just type /customoregen to reload the plugin!

# Note: If the Island's owner is offline, the cobblestone generator would be choose the first Generator-Config.

generators:
  generator1:
    # default generator
    # name of the generator (does not need to be set, just for placeholders)
    label: "Tier I Generator"
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - COBBLESTONE: 80.5
    - STONE: 16.0
    - COAL_ORE: 1.0
    - IRON_ORE: 1.0
    - GOLD_ORE: 1.0
    - REDSTONE_ORE: 0.5    
    permission: 'oregen.gen1'
    # You can also define from what level the generator should be activated. Example: Leave all permissions empty and
    # only work with the island Level. The plugin would only consider the islandLevel then.
    unlock_islandLevel: 0
  generator2:
    # vip generator, VIPS need generators.vip permission
    label: "Tier II Generator"
    blocks:
    - COBBLESTONE: 80.0
    - STONE: 14.4
    - COAL_ORE: 1.5
    - IRON_ORE: 1.0
    - GOLD_ORE: 1.0
    - REDSTONE_ORE: 1.0
    - LAPIS_ORE: 1.0
    - DIAMOND_ORE: 0.1
    permission: 'oregen.gen2'
  generator3:
    label: "Tier III Generator"
    blocks:
    - COBBLESTONE: 72.0
    - STONE: 19.5
    - COAL_ORE: 2.5
    - IRON_ORE: 1.5
    - GOLD_ORE: 1.5
    - REDSTONE_ORE: 1.0
    - LAPIS_ORE: 1.5
    - DIAMOND_ORE: 0.5
    permission: 'oregen.gen3'
  generator4:
    label: "Tier IV Generator"
    blocks:
    - COBBLESTONE: 64.0
    - STONE: 24.8
    - COAL_ORE: 3.0
    - IRON_ORE: 2.5
    - GOLD_ORE: 2.5
    - REDSTONE_ORE: 1.0
    - LAPIS_ORE: 1.5
    - DIAMOND_ORE: 0.7
    permission: 'oregen.gen4'
  generator5:
    label: "Tier V Generator"
    blocks:
    - COBBLESTONE: 62.0
    - STONE: 26.5
    - COAL_ORE: 3.0
    - IRON_ORE: 2.5
    - GOLD_ORE: 2.5
    - REDSTONE_ORE: 1.0
    - LAPIS_ORE: 1.5
    - DIAMOND_ORE: 1.0
    permission: 'oregen.gen5'
  generator6:
    label: "Tier VI Generator"
    blocks:
    - COBBLESTONE: 59.0
    - STONE: 25.0
    - COAL_ORE: 3.5
    - IRON_ORE: 3.5
    - GOLD_ORE: 3.5
    - REDSTONE_ORE: 1.0
    - LAPIS_ORE: 1.5
    - DIAMOND_ORE: 2.0
    - EMERALD_ORE: 1.0
    permission: 'oregen.gen6'
  generator7:
    label: "Sea Generator"
    blocks:
    - PRISMARINE: 84.0
    - SEA_LANTERN: 3.0
    - GRAVEL: 13.0
    permission: 'oregen.gen7'
  generator8:
    label: "End Generator"
    blocks:
    - END_STONE: 87.0
    - END_STONE_BRICKS: 7.0
    - PURPUR_BLOCK: 1.0
    - OBSIDIAN: 5.0
    permission: 'oregen.gen8'
  generator9:
    label: "Nether Generator"
    blocks:
    - NETHERRACK: 90.0
    - NETHER_BRICK: 7.0
    - GLOWSTONE: 1.0
    - NETHER_QUARTZ_ORE: 1.0
    - SOUL_SAND: 1.0
    permission: 'oregen.gen9'
# Here you can define worlds where the generator should not work
disabled-worlds:
- "world_nether"`

**Comment by mastercake10** [comment]
Thanks, I've fixed the round off bug and allowed the format `MATERIAL:<SPACE>CHANCE` in addition to the original one (`MATERIAL:CHANCE`), since people seem to tend using your format.

**Comment by samidont0817** [comment]
Thanks~
