### ISSUE TITLE
Ores generate when touching Composter

### ISSUE THREAD

**Issue by Pdani001** [mastercake10/CustomOreGen#37]
### What steps will reproduce the issue?  
1. Place Composter
2. Place water next to it

### What was supposed to happen?
No ores generate at all.

### What happened instead? 
Ores generated, like it was a cobblestone generator

### What version of this plugin are you using?  
1.3.25
![image](https://user-images.githubusercontent.com/18148949/79691589-d299fd80-8260-11ea-89ad-bd13bc76eea3.png)

### What Spigot version are you using? Paste the output of /version below.
Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Are any errors related to this plugin in your console or logs? If so, paste below.
None.

### Any additional information that you would like to provide that may be relevant to the issue?
Nothing.

**Comment by mastercake10** [comment]
fixed in d03b9e696f1fd8b2d60c46b06dacb629c18196ea
