### ISSUE TITLE
Could not pass event PlayerJoinEvent to CustomOreGen v1.3.25-SNAPSHOT

### ISSUE THREAD

**Issue by StolenSoul90** [mastercake10/CustomOreGen#38]
### What steps will reproduce the issue?  
1.  Restarting the server and having someone login automatically runs this error

### What was supposed to happen?
Nothing to my knowledge

### What happened instead? 
Nothing Server runs as it normally does

### What version of this plugin are you using?  
1.3.25
### What Spigot version are you using? Paste the output of /version below.  
1.15.2
### Are any errors related to this plugin in your console or logs? If so, paste below.  
https://pastebin.com/7fkWWwbE
### Any additional information that you would like to provide that may be relevant to the issue?
None

**Comment by mastercake10** [comment]
I think this is not an actual issue in CustomOreGen. Luckperms seems to struggle when working with zero-length strings as permissions, so please check your generators (for empty permission strings) or switch the permission plugin.

**Comment by StolenSoul90** [comment]
Yea sorry meant to close this issue. It was a luck perms thing. I did fix it and everything is running smoothly now
