### ISSUE TITLE
CustomOreGen

### ISSUE THREAD

**Issue by Ironic8b498** [mastercake10/CustomOreGen#43]
### What steps will reproduce the issue?  
1.  Create new island in MC 1.16.4 
2. Players have perms to use generator no ores appear
3. I used my player on the island and still no ores

### What was supposed to happen?
randomly they get stone and sandstone
### What happened instead? 
just cobble
### What version of this plugin are you using?  
CustomOreGen-1.3.30-SNAPSHOT
### What Spigot version are you using? Paste the output of /version below.  
1.16.4
### What plugins do you have installed? Paste the output of /plugins below.  
WorldTP-1.2.5.jar
worldguard-bukkit-7.0.5-SNAPSHOT-dist-#2079.jar
worldedit-bukkit-7.3.0-SNAPSHOT-dist-#5491.jar
Vault-1.7.3.jar
UltimateVotes-2.0.1-v.jar
SuperVanish-6.2.0.jar
Statz-1.5.5-SNAPSHOT-16.jar
PwnFilter-#3.jar
ProtocolLib-v4.5.1.jar
PluginLibrary-1.2.4.jar
PlaceholderAPI-2.10.10-DEV-118.jar
OpenInv-4.1.5.jar
NoPlugins-7.3.3.jar
MyCommand-v.5.6.7.jar
mwmoney-V3.1.jar
LuckPerms-Bukkit-5.1.106.jar
ipwhitelist-1.7-3.jar
HungerKeeperPlus-1.4.1.jar
HolographicExtension-1.10.9.jar
HolographicDisplays-2.4.5-#162.jar
FarmLimiter-1.5.1.jar
EssentialsX-2.18.1.32-#1033.jar
DeluxeTags-1.8.1-Release.jar
DeluxeMenus-1.13.3-Release.jar
DeluxeChat-1.16.2-dev.jar
CustomOreGen-1.3.30-SNAPSHOT.jar
CoreProtect-19.3.jar
ChatReaction-1.8.0.jar
BungeeTabListPlus_BukkitBridge-3.4.0.jar
BentoBox-1.15.4-SNAPSHOT-b1920.jar
Autorank-4.3.3-SNAPSHOT-52.jar
### Are any errors related to this plugin in your console or logs? If so, paste below.  
```
0:00:21] [Server thread/WARN]: [PlaceholderAPI] Task #115 for PlaceholderAPI v2.10.10-DEV-118 generated an exception
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1274) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.getServers(BungeeCordExpansion.java:108) ~[?:?]
	at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.access$100(BungeeCordExpansion.java:45) ~[?:?]
	at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion$1.run(BungeeCordExpansion.java:201) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

```

**Comment by mastercake10** [comment]
What's inside your config.yml?

**Comment by Ironic8b498** [comment]
`# You can create generators as much as you want.
# Important: All generators should be named "generator1", "generator2", etc. 
# You can define the spawnrates of any block in the blocks-section.
# The spawnrates are in percent, for example 57.3 are 57,3%.
# All values together should be 100%. If all values together are higher or lower as 100, the plugin would'nt work correctly.
# The permissions are custom, so you can make a generator for VIPS, and give them the permission "oregen.vip".
# Are you finish with configuring? Just type /customoregen to reload the plugin!

# Note: If the Island's owner is offline, the cobblestone generator would be choose the first Generator-Config.

generators:
  generator1:
    # default generator
    # name of the generator (does not need to be set, just for placeholders)
    label: "bedrock"
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - COBBLESTONE:95.0
    - STONE:5.0
    permission: 'oregen.bedrock'
    # You can also define from what level the generator should be activated. Example: Leave all permissions empty and
    # only work with the island Level. The plugin would only consider the islandLevel then.
    unlock_islandLevel: 0
  generator2:
    label: "dirt"
    blocks:
    - COBBLESTONE:90.0
    - STONE:5.0
    - SANDSTONE:5.0
    permission: 'oregen.dirt'
    unlock_islandLevel: 0
  generator3:
    label: "lava"
    blocks:
    - COBBLESTONE:86.5
    - STONE:5.0
    - SANDSTONE:7.5
    - IRON_ORE:1.0
    permission: 'oregen.lava'
    unlock_islandLevel: 0
  generator4:
    label: "iron"
    blocks:
    - COBBLESTONE:79.0
    - STONE:10.0
    - SANDSTONE:10.0
    - IRON_ORE:1.0
    permission: 'oregen.iron'
    unlock_islandLevel: 0
  generator5:
    label: "gold"
    blocks:
    - COBBLESTONE:78.7
    - STONE:10.0
    - SANDSTONE:10.0
    - IRON_ORE:1.0
    - LAPIS_ORE:0.1
    - COAL_ORE:0.2
    - GOLD_ORE:0.3
    permission: 'oregen.gold'
    unlock_islandLevel: 0
  generator6:
    label: "diamond"
    blocks:
    - COBBLESTONE:78.0
    - STONE:9.3
    - SANDSTONE:10.0
    - IRON_ORE:1.0
    - LAPIS_ORE:0.2
    - COAL_ORE:0.5
    - GOLD_ORE:0.5
    - DIAMOND_ORE:0.5
    permission: 'oregen.diamond'
    unlock_islandLevel: 0
  generator7:
    label: "grass"
    blocks:
    - COBBLESTONE:73.0
    - STONE:10.0
    - SANDSTONE:9.5
    - IRON_ORE:2.0
    - GOLD_ORE:1.0
    - DIAMOND_ORE:1.0
    - LAPIS_ORE:0.5
    - COAL_ORE:1.5
    - GRASS_BLOCK:1.5
    permission: 'oregen.grass'
    unlock_islandLevel: 0
# Here you can define worlds where the generator should not work
disabled-worlds:
- "world_nether"
`

**Comment by Ironic8b498** [comment]
I have been told it started to work, I believe all I have done was reboot the server a few times for spigot updates
