### ISSUE TITLE
No error, I didn't modify config.yml but it doesn't work :/

### ISSUE THREAD

**Issue by Hoknyy** [mastercake10/CustomOreGen#5]
Hi,

I've put your plugin on my skyblock server but it doesn't work, I haven't any error message, the plugin even told me the number of generators loaded when I do /customoregen.
I've tried to restart my server, to add the permission to a player / to a group, I've tried with my op account, nothing seems work :/

(Server in 1.8.8 with the latest version of Askyblock (I uptaded yesterday))

Thx for reading !

**Comment by mastercake10** [comment]
Have you tried using the default config.yml?

**Comment by Hoknyy** [comment]
Yes sure, I've tried with the default config firstly and it didn't work

2018-03-23 15:54 GMT+01:00 MasterCake <notifications@github.com>:

**Comment by Hoknyy** [comment]
Hello, So do you have an advice ?
