### ISSUE TITLE
Could you please change 100% to 300%? There's too much stuff to fit in.

### ISSUE THREAD

**Issue by BigAppleClass** [mastercake10/CustomOreGen#50]
enable-stone-generator: false
generators:
  generator1:
    label: "mo"
    blocks:
      - COBBLED_DEEPSLATE: 13.0
      
      # 泥土
      # 草方块
      # 菌丝
      # 绯红菌岩
      # 诡异菌岩
      # 沙子
      # 红沙
      # 沙砾
      # 灵魂土
      # 灵魂沙
      # 下界岩
      # 黏土块
      - DIRT: 1.0
      - GRASS_BLOCK: 1.0
      - MYCELIUM: 1.0
      - CRIMSON_NYLIUM: 1.0
      - WARPED_NYLIUM: 1.0
      - SAND: 1.0
      - RED_SAND: 1.0
      - GRAVEL: 1.0
      - SOUL_SOIL: 1.0
      - SOUL_SAND: 1.0
      - NETHERRACK: 1.0
      - CLAY: 1.0

      # 煤矿石
      # 深层煤矿石
      # 铁矿石
      # 深层铁矿石
      # 铜矿石
      # 深层铜矿石
      # 金矿石
      # 深层金矿石
      # 下界金矿石
      # 红石矿石
      #  深层红石矿石
      #  青金石矿石
      #  深层青金石矿石
      #  钻石矿石
      #  深层钻石矿石
      #  下界石英矿石
      - COAL_ORE: 1.0
      - DEEPSLATE_COAL_ORE: 1.0
      - IRON_ORE: 1.0
      - DEEPSLATE_IRON_ORE: 1.0
      - COPPER_ORE: 1.0
      - DEEPSLATE_COPPER_ORE: 1.0
      - GOLD_ORE: 1.0
      - DEEPSLATE_GOLD_ORE: 1.0
      - NETHER_GOLD_ORE: 1.0
      - REDSTONE_ORE: 1.0
      - DEEPSLATE_REDSTONE_ORE: 1.0
      - LAPIS_ORE: 1.0
      - DEEPSLATE_LAPIS_ORE: 1.0
      - DIAMOND_ORE: 1.0
      - DEEPSLATE_DIAMOND_ORE: 1.0
      - NETHER_QUARTZ_ORE: 1.0
      
      # 橡木原木
      # 云杉原木
      # 白桦原木
      # 丛林原木
      # 金合欢原木
      # 深色橡木原木
      # 红树原木
      # 绯红菌柄
      # 诡异菌柄
      - OAK_LOG: 1.0
      - SPRUCE_LOG: 1.0
      - BIRCH_LOG: 1.0
      - JUNGLE_LOG: 1.0
      - ACACIA_LOG: 1.0
      - DARK_OAK_LOG: 1.0
      - MANGROVE_LOG: 1.0
      - CRIMSON_STEM: 1.0
      - WARPED_STEM: 1.0
      
      # 去皮橡木原木
      # 去皮云杉原木
      # 去皮白桦原木
      # 去皮丛林原木
      # 去皮金合欢原木
      # 去皮深色橡木原木
      # 去皮红树原木
      # 去皮绯红菌柄
      # 去皮诡异菌柄
      - STRIPPED_OAK_LOG: 1.0
      - STRIPPED_SPRUCE_LOG: 1.0
      - STRIPPED_BIRCH_LOG: 1.0
      - STRIPPED_JUNGLE_LOG: 1.0
      - STRIPPED_ACACIA_LOG: 1.0
      - STRIPPED_DARK_OAK_LOG	: 1.0
      - STRIPPED_MANGROVE_LOG: 1.0
      - STRIPPED_CRIMSON_STEM: 1.0
      - STRIPPED_WARPED_STEM: 1.0

      
      # 海晶灯
      # 蓝冰
      # 陶瓦
      # 石英块
      # 砂岩
      # 红砂岩
      - SEA_LANTERN: 1.0
      - BLUE_ICE: 1.0
      - TERRACOTTA: 1.0
      - QUARTZ_BLOCK: 1.0
      - SANDSTONE: 1.0
      - RED_SANDSTONE: 1.0
      
      # 花岗岩
      # 闪长岩
      # 安山岩
      # 方解石
      # 凝灰岩
      # 泥巴
      # 玄武岩
      # 荧石
      # 黑石
      - GRANITE: 1.0
      - DIORITE: 1.0
      - ANDESITE: 1.0
      - CALCITE: 1.0
      - TUFF: 1.0
      - MUD: 1.0
      - BASALT: 1.0
      - GLOWSTONE: 1.0
      - BLACKSTONE: 1.0
      
      # 白色混凝土
      # 橙色混凝土
      # 品红色混凝土
      # 淡蓝色混凝土
      # 黄色混凝土
      # 黄绿色混凝土
      # 粉红色混凝土
      # 灰色混凝土
      # 淡灰色混凝土
      # 青色混凝土
      # 紫色混凝土
      # 蓝色混凝土
      # 棕色混凝土
      # 绿色混凝土	
      # 红色混凝土
      # 黑色混凝土
      - WHITE_CONCRETE: 1.0
      - ORANGE_CONCRETE: 1.0
      - MAGENTA_CONCRETE: 1.0
      - LIGHT_BLUE_CONCRETE: 1.0
      - YELLOW_CONCRETE: 1.0
      - LIME_CONCRETE: 1.0
      - PINK_CONCRETE: 1.0
      - GRAY_CONCRETE: 1.0
      - LIGHT_GRAY_CONCRETE: 1.0
      - CYAN_CONCRETE: 1.0
      - PURPLE_CONCRETE: 1.0
      - BLUE_CONCRETE: 1.0
      - BROWN_CONCRETE: 1.0
      - GREEN_CONCRETE: 1.0
      - RED_CONCRETE: 1.0
      - BLACK_CONCRETE: 1.0
      
      # 橡木木板
      # 云杉木板
      # 白桦木板
      # 丛林木板
      # 金合欢木板
      # 深色橡木木板
      # 红树木板
      # 绯红木板
      # 诡异木板
      - OAK_PLANKS: 1.0
      - SPRUCE_PLANKS: 1.0
      - BIRCH_PLANKS: 1.0
      - JUNGLE_PLANKS: 1.0
      - ACACIA_PLANKS: 1.0
      - DARK_OAK_PLANKS: 1.0
      - MANGROVE_PLANKS: 1.0
      - CRIMSON_PLANKS: 1.0
      - WARPED_PLANKS: 1.0

**Comment by mastercake10** [comment]
You can use decimal numbers for the chances, so `0.5`, `0.3`, `0.2`, `0.05` etc. This way you can fit more blocks. Just make sure that all together it adds up to `100.0`.
