### ISSUE TITLE
There seems to be a conflict with BentoBox

### ISSUE THREAD

**Issue by BigAppleClass** [mastercake10/CustomOreGen#55]
The normal server works, but BentoBox will report an error

**Comment by mastercake10** [comment]
what is the error?

**Comment by BigAppleClass** [comment]
[2023-06-10-8.log](https://github.com/mastercake10/CustomOreGen/files/11712554/2023-06-10-8.log)

**Comment by mastercake10** [comment]
it somehow needs the VisitAddon, try to install it.

**Comment by BigAppleClass** [comment]
Ok, thanks. Can you give me a download link

**Comment by mastercake10** [comment]
put it in your Bentobox folder:
https://ci.codemc.io/job/BentoBoxWorld/job/Visit/lastSuccessfulBuild/artifact/target/Visit-1.7.0-SNAPSHOT-b98.jar
