### ISSUE TITLE
Disable the ore generating if lava flows on water.

### ISSUE THREAD

**Issue by poma123** [mastercake10/CustomOreGen#7]
The acidisland plugin already disable the cleanstone generating, if lava flows to water. But, if lava flows to water, the configured blocks still generated in this situation, and the players can benefit from this.
![image](https://user-images.githubusercontent.com/25465545/38869057-aba7015e-4249-11e8-805a-f9082a5ae412.png)

![image](https://user-images.githubusercontent.com/25465545/38868852-e7c5667c-4248-11e8-9354-ab4a0e9ff0d4.png)

![image](https://user-images.githubusercontent.com/25465545/38868835-d941a3f4-4248-11e8-879f-db2f922f06f4.png)

**Comment by mastercake10** [comment]
There's a possibility that the bug was fixed in version 1.2.39, so please try this out.

**Comment by poma123** [comment]
Fantastic!
Thanks!
